name: chatico
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_route: ^8.3.0
  awesome_flutter_extensions: ^1.2.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.1.0
  country_picker: ^2.0.26
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_converter: ^0.3.3
  flutter_lorem: ^2.0.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  mobile_scanner: ^5.1.1
  number_pad_keyboard: ^0.0.6
  path_provider: ^2.1.3
  pinput: ^5.0.0
  pretty_qr_code: ^3.3.0
  skeletonizer: ^1.4.1+1
  super_context_menu: ^0.8.17
  uuid: ^4.4.2

dev_dependencies:
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wallpapers/
